
browser=firefox
selenide.headless=true
#selenide.remote=http://selenoid:4444/wd/hub
browserSize=1366x768

# Chrome version
capabilities.chrome.browserVersion=latest
#chrome.capabilities=goog:chromeOptions.args=["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","--disable-extensions"]

# Firefox version
capabilities.firefox.browserVersion=120.0
